### ISSUE TITLE
ERROR: dependency 'TStools' is not available for package 'thief'

### ISSUE THREAD

**Issue by RhombicTriacontahedron** [robjhyndman/thief#1]
Hi there, 
Not sure this is the proper channel...complete newbie here. sorry.

With input 

`install.packages("devtools")
devtools::install_github("robjhyndman/thief")
library(thief)`

RStudio gives:

> > # install.packages("devtools")
> > 
> > devtools::install_github("robjhyndman/thief")
> > Downloading GitHub repo robjhyndman/thief@master
> > from URL https://api.github.com/repos/robjhyndman/thief/zipball/master
> > Installing thief
> > "C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet  \
> >   CMD INSTALL  \
> >   "C:/Users/dh/AppData/Local/Temp/Rtmpaidvgs/devtools21b419b2650a/robjhyndman-thief-9302849"  \
> >   --library="C:/Users/dh/Documents/R/win-library/3.3" --install-tests 
> > ERROR: dependency 'TStools' is not available for package 'thief'
> > - removing 'C:/Users/dh/Documents/R/win-library/3.3/thief'
> >   Error: Command failed (1)

What should I try next?

**Comment by RhombicTriacontahedron** [comment]
Figured out...
Too much googling for TStools..then Rtools... then a bunch of other dependencies...
But anyway. I'll save the bullets for real questions.
I'm glad I could figure it out myself...
Thanks in advance.
Fantastic work..
Certainly much more than I could ever accomplish by myself

**Comment by robjhyndman** [comment]
I've now removed the TStools dependency, and used only CRAN packages.

**Comment by RhombicTriacontahedron** [comment]
Thanks.
I'm sure that may save a small headache for some of the new users, at the margin.
