### ISSUE TITLE
data sampled every five seconds

### ISSUE THREAD

**Issue by rds99** [robjhyndman/thief#10]
Hi,
Can this be used for data sampled every five seconds for two hours, for forecasting for next 5 minutes?

**Comment by robjhyndman** [comment]
Yes. Just specify the frequency in seconds, and what periodicities are present. e.g., if there is a seasonal period corresponding to minutes, and another one to hours, then set `frequency=24*60*60/5`

**Comment by rds99** [comment]
thanks
is there a complete reference manual?
and some worked out example for high frequency data?
Thanks

**Comment by robjhyndman** [comment]
All the documentation is at http://pkg.robjhyndman.com/thief/
There are no worked examples for high frequency data

**Comment by robjhyndman** [comment]
Something like this might be what you are after:
```r
library(thief)
fivemindata <- ts(rnorm(50000, 10, 1), frequency=24*60*60/5)
fit <- thief(fivemindata)
```
