### ISSUE TITLE
Install thief in rstudio

### ISSUE THREAD

**Issue by swagat123** [robjhyndman/thief#11]
Will this 'thief' package will be installed in r studio. I tried this

>  install.packages('thief', dependencies = TRUE)

in r studio but i got installation error. 

Thanks

**Comment by swagat123** [comment]
Below error i got

```

> install.packages('thief', dependencies = TRUE)
Installing package into ‘C:/Users/User0/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘thief’ is not available (for R version 3.2.2)
```

**Comment by robjhyndman** [comment]
Your version of R is far too old. Please update to the current version.

**Comment by swagat123** [comment]
Thank you Professor.I installed the higher version of R and it worked.
