### ISSUE TITLE
non-conformable arrays 

### ISSUE THREAD

**Issue by yasineahmed** [robjhyndman/thief#13]
When running hts forecast would get  Error in `-.default`(y, fits) : non-conformable arrays 
is the thief function not returning fitted values in an easily accessible form resulting in the described error?

Code: 
 forecast(object  =  x,
                 h       = 12,
                 method  = "comb",
                 keep.fitted = TRUE,
                 weights = "mint",
                 positive =  TRUE,
                 FUN = function(i) thief(i,m=12))

**Comment by robjhyndman** [comment]
thief needs full years and will throw away partial years at the start. If you do the same before running your code it should work. Note that you should also include the h argument in thief.

**Comment by yasineahmed** [comment]
Issue Resolved. Thank you for the additional help.

**Comment by yasineahmed** [comment]
Is there a work around for thief needing full years to generate a forecast? The only way I am able to currently run the model following the steps described above of dropping  partial years.
`Hierarchical Time Series 
4 Levels 
Number of nodes at each level: 1 6 447 3184 
Total number of series: 3638 
Number of observations per series: 37 `

> forecast.gts(
  object  =  gts,
  h       = h,
  keep.fitted = TRUE,
  method  = "comb",
  weights = "mint",
  fmethod =  NULL,
  positive = TRUE,
  parallel = TRUE,
  num.cores = 50,
  FUN = function(i) thief(log(i),m = 12,h = h)
)

`Error in `-.default`(y, fits) : non-conformable arrays`

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/thief/commit/3cf654c53c0448182bd3847fa692ddee0badcfb2

**Comment by yasineahmed** [comment]
Thank you for quickly resolving this.
