### ISSUE TITLE
forecast function of thief

### ISSUE THREAD

**Issue by Arsa-Nik** [robjhyndman/thief#14]
Is it possible to run thief with `forecastfunction`  equal to user-defined stlf function while stlf function has its own user-defined `forecastfunction` which is tbats?

I get below error in stlf function when running thief on it.
`Error in stlf(x, h = h) : y is not a seasonal ts object` 

Thanks,

**Comment by robjhyndman** [comment]
Yes. But you will need an alternative for when the series is aggregated to annual data. Here is an example:
``` r
library(thief)
mystlf <- function(y, h) {
  if(frequency(y) > 1) {
    fc <- stlf(y, h=h, forecastfunction = 
        function(y, h=h, ...) {
          forecast(tbats(y), h=h, ...)
        })
  } else {
    fc <- forecast(tbats(y), h=h)
  }
  return(fc)
}

thief(USAccDeaths, forecastfunction=mystlf)
#>            Jan       Feb       Mar       Apr       May       Jun       Jul
#> 1979  8141.985  7384.303  8172.561  8366.430  9245.155  9652.677 10602.909
#> 1980  8097.501  7353.636  8167.286  8360.785  9255.064  9673.014 10614.649
#>            Aug       Sep       Oct       Nov       Dec
#> 1979  9835.319  8814.765  9066.546  8600.660  8920.363
#> 1980  9856.117  8844.632  9101.228  8638.985  8965.524
```

<sup>Created on 2019-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Arsa-Nik** [comment]
Thank you for your response and the additional help.
