### ISSUE TITLE
Prediction intervals

### ISSUE THREAD

**Issue by yishusong** [robjhyndman/thief#15]
At the end of this post: https://robjhyndman.com/hyndsight/thief/ , the reconciled forecasts seem to have prediction intervals. However, I can't find an argument in thief functions that enable prediction intervals.

**Comment by robjhyndman** [comment]
They are simply the original prediction intervals from the model used on the most disaggregated series, adjusted for any changes in the mean after reconciliation. If you use `reconcilethief` rather than `thief`, these are produced.
