### ISSUE TITLE
Bug in the thief() function using a quarterly time-series

### ISSUE THREAD

**Issue by pgg1309** [robjhyndman/thief#2]
I'm getting an odd behavior when trying to use the thief() function. What is interesting is that the function runs fine with my time series but when I add one observation to the time-series I get the error message:

> "Error in `[.default`(fc$lower, , 1) : incorrect number of dimensions"

The reproducible bug (MRE), with data, can be found in 

MRE URL: 
https://gist.github.com/pgg1309/3ef3d0c5baf459af0262ffd08275ceee

Many thanks.
Paulo

**Comment by robjhyndman** [comment]
Thanks. Now fixed in https://github.com/robjhyndman/thief/commit/94da45809ce33b5b05fb895ceee0c938f17b157f
