### ISSUE TITLE
Better Yearly Data Handling

### ISSUE THREAD

**Issue by AnscombesGimlet** [robjhyndman/thief#7]
Currently the thief() function cannot handle yearly data, presumably because there is no hierarchy to estimate. Instead of it erroring out, could it just trigger a warning and then default to the forecast function used?

    data(M3)
    thief(M3[[1]]$x, h = 1)
Error in thief(M3[[1]]$x, h = 1) : 
  Seasonal period (m) must be greater than 1

**Comment by robjhyndman** [comment]
Defaulting to the forecast function would be highly misleading. thief does temporal hierarchical forecasting. If it can't do that, an error is the correct response.
