### ISSUE TITLE
How to incorporate regressors?

### ISSUE THREAD

**Issue by 123saga** [robjhyndman/thief#9]
Hi Rob, 

Thanks for another awesome package, I was wondering if there is a way to use regressors while aggregating temporal hierarchical forecasts ?

Thanks,
Sagar

**Comment by robjhyndman** [comment]
The problem is that there is no unique way of combining the regressors across time. Should they be summed, averaged, or something else? You could do the various forecasts yourself, and then use `reconcilethief()` to reconcile them.
